default: &default
  adapter: postgresql
  encoding: unicode
  database: vkation_development
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: vkation_production  
  username: sharetribe
  password: secret
